name: Testing checkout
on:
  workflow_dispatch:   
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
    - name: before checkout
      run: ls -l
    - name: Get Code
      uses: actions/checkout@v3
    - name: after checkout
      run: ls -l
